import type { Provider, Skill, Project } from './types'

export const PROVIDERS: Provider[] = [
  { id: 'claude-sonnet-4.5', label: 'claude-sonnet-4.5', kind: 'cloud' },
  { id: 'claude-opus-4.1', label: 'claude-opus-4.1', kind: 'cloud' },
  { id: 'gpt-4o', label: 'gpt-4o', kind: 'cloud' },
  { id: 'gemini-2.5-pro', label: 'gemini-2.5-pro', kind: 'cloud' },
  { id: 'opencode', label: 'opencode', kind: 'local' },
  { id: 'claude-code', label: 'Claude Code', kind: 'local' },
  { id: 'aider', label: 'aider', kind: 'local' },
  { id: 'ollama', label: 'Ollama · llama-3.3', kind: 'local' },
]

export const WF_ROLES = ['Lead', 'Planung', 'Design', 'Code', 'Review', 'QA', 'Sonstige']

export const seedSkills: Skill[] = [
  { name: 'web-search', cat: 'Web', desc: 'Suche und lese Webseiten in Echtzeit.', installs: '48k', installed: true },
  { name: 'brainstorm', cat: 'Planung', desc: 'Lösungswege und Ideen für ein Ticket generieren.', installs: '26k', installed: true },
  { name: 'grillme', cat: 'Planung', desc: 'Annahmen kritisch hinterfragen und den Scope schärfen.', installs: '21k', installed: true },
  { name: 'pdf-extract', cat: 'Files', desc: 'Text und Tabellen aus PDF-Dokumenten extrahieren.', installs: '31k', installed: true },
  { name: 'summarize', cat: 'AI', desc: 'Lange Dokumente auf das Wesentliche verdichten.', installs: '40k', installed: true },
  { name: 'sql-query', cat: 'Data', desc: 'Read-only Abfragen auf verbundene Datenbanken.', installs: '22k', installed: true },
  { name: 'send-email', cat: 'Comms', desc: 'E-Mails über SMTP oder Resend versenden.', installs: '19k', installed: true },
  { name: 'code-review', cat: 'Code', desc: 'Diffs prüfen und Kommentare vorschlagen.', installs: '15k', installed: true },
  { name: 'slack-post', cat: 'Comms', desc: 'Nachrichten in Slack-Kanäle posten.', installs: '12k', installed: true },
  { name: 'image-gen', cat: 'AI', desc: 'Bilder aus Text-Prompts erzeugen.', installs: '27k', installed: false },
  { name: 'csv-transform', cat: 'Data', desc: 'CSV-Dateien parsen, filtern und umformen.', installs: '9k', installed: false },
]

export const seedProjects: Project[] = [
  {
    id: 'p1',
    name: 'Q3 Marktreport',
    hue: 274,
    jira: { connected: true, url: 'https://nova.atlassian.net/PROJ/MKT' },
    slack: { connected: true, channel: '#q3-report' },
    designMd:
      '# Q3 Marktreport — Design & Ton\n\n## Stil\n- Nüchtern, faktenbasiert, keine Superlative\n- Zahlen immer mit Quelle und Stichdatum\n\n## Struktur\n1. Executive Summary (max. 1 Seite)\n2. Marktüberblick\n3. Wettbewerber-Matrix\n4. Empfehlungen',
    instructions:
      'Immer auf Deutsch antworten. Quellen als Fußnoten angeben. Keine vertraulichen Kundennamen nennen. Vor dem Versenden von E-Mails immer Rückfrage.',
    envs: [
      { key: 'ANTHROPIC_API_KEY', value: 'sk-ant-••••4f2a' },
      { key: 'SERP_API_KEY', value: '••••9c21' },
    ],
    jiraInbox: [
      { key: 'MKT-231', title: 'Preisvergleich Wettbewerber Q3', type: 'Story' },
      { key: 'MKT-244', title: 'Chart-Assets für den Report erstellen', type: 'Task' },
    ],
    roles: ['Lead', 'Recherche', 'Outreach', 'Data'],
    agents: [
      { id: 'a1', name: 'Atlas', role: 'Research Analyst', wf: 'Lead', provider: 'claude-sonnet-4.5', status: 'running', skills: ['web-search', 'pdf-extract', 'summarize'], hue: 274 },
      { id: 'a2', name: 'Mercury', role: 'Outreach & E-Mail', wf: 'Outreach', provider: 'gpt-4o', status: 'idle', skills: ['send-email', 'summarize'], hue: 200 },
      { id: 'a4', name: 'Ledger', role: 'Finance Ops', wf: 'Data', provider: 'ollama', status: 'error', skills: ['sql-query', 'csv-transform'], hue: 75 },
    ],
    tickets: [
      {
        id: 'TCK-09',
        title: 'Wettbewerbsanalyse der Top-5 Anbieter',
        status: 'in_progress',
        prio: 'Hoch',
        agentId: 'a1',
        skill: 'pdf-extract',
        elapsed: '1:12',
        tokens: '18.4k',
        updated: 'vor 1 Min',
        desc: 'Fundierte Wettbewerbsanalyse der fünf führenden Orchestrierungs-Plattformen inkl. Marktanteil, Preismodell und Positionierung für den Q3-Report.',
        activity: [
          { type: 'thought', time: '14:30', action: 'plante das Vorgehen', text: 'Ich brauche aktuelle Marktdaten. Zuerst identifiziere ich die führenden Anbieter und ihre jüngsten Ankündigungen.' },
          { type: 'skill', time: '14:31', action: 'nutzte web-search', skillName: 'web-search', args: '{ query: "top orchestration platforms 2026" }', result: '8 Ergebnisse durchsucht · 4 relevante Primärquellen identifiziert.', shot: { id: 'p1r1_shot', caption: 'Screenshot: Suchergebnisse & Anbieter-Landschaft' } },
          { type: 'skill', time: '14:33', action: 'extrahierte den Gartner-Report', skillName: 'pdf-extract', args: '{ file: "gartner_q2_2026.pdf" }', result: 'Umsatz-, Marktanteils- und Wachstumsdaten für 5 Anbieter extrahiert.', code: { file: 'market_share.json', body: '{\n  "OrchPlatform": { "share": 0.28, "growth": 0.41 },\n  "AgentHub":     { "share": 0.19, "growth": 0.33 },\n  "FlowworksAI":  { "share": 0.14, "growth": 0.22 }\n}' } },
          { type: 'message', time: '14:36', action: 'fasste Zwischenstand zusammen', text: 'Erste Erkenntnisse: Der Markt konsolidiert sich um drei Anbieter mit zusammen 61% Anteil. Preismodelle verschieben sich klar in Richtung nutzungsbasiert. Ich formuliere jetzt den Analyse-Entwurf…' },
          { type: 'handoff', time: '14:37', to: 'a2', text: 'Übergabe an Mercury: Entwurf steht — bitte die Vorab-Ankündigung an die Abonnenten vorbereiten.' },
        ],
      },
      {
        id: 'TCK-15',
        title: 'Preisdaten aus interner DB abgleichen',
        status: 'blocked',
        prio: 'Hoch',
        agentId: 'a4',
        skill: 'sql-query',
        elapsed: '0:41',
        tokens: '4.3k',
        updated: 'vor 1 Std',
        desc: 'Gleiche die extrahierten Preisdaten mit der internen Finance-Datenbank ab, um Abweichungen zu markieren.',
        activity: [
          { type: 'thought', time: '13:02', action: 'plante die Abfrage', text: 'Ich verbinde mich mit der Finance-DB und lese die aktuellen Preistabellen.' },
          { type: 'skill', time: '13:02', action: 'nutzte sql-query', skillName: 'sql-query', args: '{ table: "pricing" }', result: 'Verbindung fehlgeschlagen — Zugriff verweigert (401).', ok: false },
          { type: 'error', time: '13:03', text: 'Ich konnte den Abgleich nicht abschließen: die Datenbank-Zugangsdaten sind abgelaufen. Bitte einen gültigen Read-Only-Key hinterlegen, dann starte ich neu.' },
        ],
      },
      {
        id: 'TCK-07',
        title: 'Outreach an 40 Report-Abonnenten',
        status: 'done',
        prio: 'Mittel',
        agentId: 'a2',
        skill: 'send-email',
        elapsed: '3:48',
        tokens: '31.2k',
        updated: 'vor 22 Min',
        desc: 'Personalisiere und versende die Vorab-Ankündigung des Q3-Reports an 40 registrierte Abonnenten.',
        activity: [
          { type: 'skill', time: '15:02', action: 'nutzte summarize', skillName: 'summarize', args: '{ source: "crm_notes" }', result: 'Kontext pro Empfänger zusammengefasst.' },
          { type: 'skill', time: '15:03', action: 'nutzte send-email', skillName: 'send-email', args: '{ batch: 40, template: "q3_teaser" }', result: '40 E-Mails versendet · 0 Fehler.', code: { file: 'welcome.tsx', body: 'export const Teaser = ({ name }) => (\n  <Email>\n    <Text>Hi {name}, der Q3-Report kommt bald.</Text>\n    <Button href={link}>Vorab sichern</Button>\n  </Email>\n);' } },
          { type: 'message', time: '15:06', action: 'meldete Abschluss', text: 'Fertig. Alle 40 E-Mails wurden personalisiert versendet. 6 Öffnungen bereits registriert.' },
        ],
      },
      { id: 'TCK-14', title: 'Quellenliste kuratieren', status: 'backlog', prio: 'Niedrig', agentId: 'a1', skill: 'web-search', elapsed: '—', tokens: '—', updated: 'gestern', desc: 'Sammle und bewerte verlässliche Primärquellen für die Analyse.', activity: [] },
    ],
  },
  {
    id: 'p2',
    name: 'Codebase-Migration',
    hue: 150,
    jira: { connected: true, url: 'https://nova.atlassian.net/PROJ/ENG' },
    slack: { connected: false, channel: '#eng-migration' },
    designMd:
      '# Codebase-Migration — Konventionen\n\n## Code-Stil\n- TypeScript strict, keine any\n- Conventional Commits\n- Jede PR mit Tests\n\n## Sicherheit\n- Keine Secrets im Code\n- Auth-Änderungen immer Review durch 2 Agenten',
    instructions:
      'Nur Read-only auf main. Änderungen ausschließlich über PRs. Bei Sicherheitsfunden sofort Sentinel hinzuziehen. Deutsch kommentieren.',
    envs: [
      { key: 'GITHUB_TOKEN', value: 'ghp_••••7b3d' },
      { key: 'CI_WEBHOOK', value: 'https://ci.nova••••' },
    ],
    jiraInbox: [
      { key: 'ENG-501', title: 'Session-Timeout konfigurierbar machen', type: 'Story' },
      { key: 'ENG-518', title: 'Flaky Test in auth.spec beheben', type: 'Bug' },
    ],
    roles: ['Lead', 'Planung', 'Design', 'Code', 'Review', 'QA'],
    agents: [
      { id: 'b1', name: 'Forge', role: 'Code Review', wf: 'Code', provider: 'claude-code', status: 'running', skills: ['code-review'], hue: 150 },
      { id: 'b2', name: 'Sentinel', role: 'Security Auditor', wf: 'Review', provider: 'opencode', status: 'idle', skills: ['code-review', 'web-search'], hue: 20 },
      { id: 'b3', name: 'Pixel', role: 'Design / UI', wf: 'Design', provider: 'claude-sonnet-4.5', status: 'running', skills: ['image-gen', 'summarize'], hue: 320 },
      { id: 'b4', name: 'Proof', role: 'QA / Test', wf: 'QA', provider: 'aider', status: 'idle', skills: ['code-review'], hue: 200 },
      { id: 'b5', name: 'Sage', role: 'Produkt / Planung', wf: 'Lead', provider: 'claude-opus-4.1', status: 'idle', skills: ['brainstorm', 'grillme', 'summarize'], hue: 270 },
    ],
    tickets: [
      {
        id: 'TCK-30',
        title: 'Passwordless-Login: Konzept',
        status: 'backlog',
        prio: 'Mittel',
        agentIds: ['b5'],
        skill: 'brainstorm',
        elapsed: '0:38',
        tokens: '5.1k',
        updated: 'vor 10 Min',
        desc: 'In der Planungsphase: Lösungswege für passwortlosen Login sammeln und den Scope schärfen, bevor das Ticket in die Umsetzung geht.',
        planQuestions: [
          { skill: 'brainstorm', q: 'Welche passwortlosen Verfahren sollen wir unterstützen (Passkeys, Magic-Link, OTP)?' },
          { skill: 'grillme', q: 'Was passiert, wenn ein Nutzer sein Gerät verliert — wie sieht der Recovery-Flow aus?' },
          { skill: 'grillme', q: 'Welche Alt-Login-Wege müssen für die Migration erhalten bleiben?' },
          { skill: 'brainstorm', q: 'Was ist der kleinste sinnvolle erste Schritt für ein Pilot-Rollout?' },
        ],
        plan: [
          'Passkeys als primäres Verfahren, Magic-Link als Fallback',
          'Recovery über verifizierte Zweit-E-Mail',
          'Feature-Flag für schrittweisen Rollout (5% → 100%)',
          'Alt-Login 2 Release-Zyklen parallel halten',
        ],
        activity: [
          { type: 'skill', actor: 'b5', phase: 'plan', time: '08:02', action: 'nutzte brainstorm', skillName: 'brainstorm', args: '{ topic: "passwordless login" }', result: '5 Ansätze gesammelt: Magic-Link, Passkeys, OTP, OAuth-only, WebAuthn.' },
          { type: 'skill', actor: 'b5', phase: 'plan', time: '08:10', action: 'nutzte grillme', skillName: 'grillme', args: '{ assumptions: 4 }', result: 'Annahmen hinterfragt — Passkeys als primär, Magic-Link als Fallback empfohlen.' },
          { type: 'message', actor: 'b5', phase: 'plan', time: '08:15', action: 'hält den Zwischenstand fest', text: 'Noch in Planung. Beantworte die offenen Fragen im Terminal, dann schiebe ich das Ticket auf „Ready for Dev".' },
        ],
      },
      {
        id: 'TCK-12',
        title: 'Auth-Modul: Login-Flow überarbeiten',
        status: 'in_progress',
        prio: 'Hoch',
        agentIds: ['b5', 'b1', 'b3', 'b4'],
        skill: 'code-review',
        elapsed: '2:38',
        tokens: '26.7k',
        updated: 'gerade eben',
        desc: 'Login-Flow refactoren (PR #482): Planung, Code Review der Sicherheit, überarbeitetes UI und QA-Durchlauf vor dem Merge.',
        plan: [
          'Rate-Limit am Login-Endpoint (max. 5 Versuche)',
          'Offene Redirects gegen Whitelist prüfen',
          'Neuer Fehler- und Sperr-State im UI',
          'E2E-Tests für den kompletten Login-Flow',
        ],
        activity: [
          { type: 'skill', actor: 'b5', phase: 'plan', time: '08:40', action: 'nutzte brainstorm', skillName: 'brainstorm', args: '{ topic: "login hardening" }', result: '6 Lösungsansätze gesammelt, 3 priorisiert.' },
          { type: 'skill', actor: 'b5', phase: 'plan', time: '08:52', action: 'nutzte grillme', skillName: 'grillme', args: '{ assumptions: 3 }', result: 'Annahmen geprüft — Rate-Limit und Redirect-Whitelist als Muss identifiziert.' },
          { type: 'message', actor: 'b5', phase: 'plan', time: '08:58', action: 'schloss die Planung ab', text: 'Scope steht: Rate-Limit, Redirect-Whitelist und neuer Fehler-State. Ticket ist ready for dev — Übergabe an die Umsetzung.' },
          { type: 'thought', actor: 'b1', phase: 'build', time: '09:12', action: 'plante das Review', text: 'Ich beginne mit dem Diff der geänderten Auth-Dateien und prüfe zuerst die Session-Behandlung.' },
          { type: 'skill', actor: 'b1', phase: 'build', time: '09:12', action: 'nutzte code-review', skillName: 'code-review', args: '{ pr: 482, files: 7 }', result: '7 Dateien analysiert · 2 Findings mittlerer Schwere.', code: { file: 'auth/login.ts · Finding', body: '- app.post("/login", handler)\n+ app.post("/login", rateLimit({ max: 5 }), handler)\n\n// Kein Rate-Limit am Login-Endpoint (Zeile 42)' } },
          { type: 'handoff', actor: 'b1', to: 'b3', phase: 'build', time: '09:20', text: 'Übergabe an Pixel: Bitte den Login-Screen mit Fehler- und Sperr-Status gestalten.' },
          { type: 'skill', actor: 'b3', phase: 'build', time: '09:34', action: 'nutzte image-gen', skillName: 'image-gen', args: '{ screen: "login", states: 3 }', result: '3 UI-Varianten für Login inkl. Rate-Limit-Hinweis erzeugt.', shot: { id: 'tck12_shot', caption: 'Screenshot: Login-Screen — neuer Fehler-State' } },
          { type: 'message', actor: 'b3', phase: 'build', time: '09:41', action: 'lieferte das Design', text: 'Neuer Login-State steht: klare Sperr-Meldung nach 5 Fehlversuchen, zugänglicher Fokus-Zustand. Bereit für QA.' },
          { type: 'handoff', actor: 'b3', to: 'b4', phase: 'review', time: '09:42', text: 'Übergabe an Proof: Bitte den überarbeiteten Flow inkl. Rate-Limit testen.' },
          { type: 'skill', actor: 'b4', phase: 'review', time: '10:02', action: 'nutzte code-review', skillName: 'code-review', args: '{ suite: "e2e/auth", cases: 14 }', result: '14 Testfälle · 13 grün, 1 offen (Redirect-Whitelist).', code: { file: 'e2e/auth.spec.ts', body: '✓ blockt nach 5 Fehlversuchen\n✓ zeigt Sperr-Hinweis\n✗ offener Redirect wird abgewiesen  // TODO' } },
          { type: 'message', actor: 'b4', phase: 'review', time: '10:08', action: 'meldete QA-Ergebnis', text: 'Fast fertig: 13 von 14 Tests grün. Der offene Redirect muss noch auf eine Whitelist. Danach ist der PR merge-bereit.' },
        ],
      },
      {
        id: 'TCK-08',
        title: 'Dependency-Audit',
        status: 'review',
        prio: 'Hoch',
        agentId: 'b2',
        skill: 'code-review',
        elapsed: '2:10',
        tokens: '12.6k',
        updated: 'vor 3 Std',
        desc: 'Scanne alle Dependencies auf bekannte Schwachstellen und erstelle einen Kurzbericht.',
        activity: [
          { type: 'skill', time: '06:40', action: 'nutzte web-search', skillName: 'web-search', args: '{ query: "CVE lodash 2026" }', result: '2 relevante Advisories gefunden.' },
          { type: 'skill', time: '06:41', action: 'nutzte code-review', skillName: 'code-review', args: '{ scope: "dependencies" }', result: '1 veraltete Abhängigkeit mit bekannter CVE identifiziert.' },
          { type: 'message', time: '06:42', action: 'meldete Abschluss', text: 'Abgeschlossen. Eine kritische Abhängigkeit sollte aktualisiert werden — Details im Bericht.' },
        ],
      },
      { id: 'TCK-21', title: 'Legacy-Endpoints kartieren', status: 'backlog', prio: 'Mittel', agentId: 'b1', skill: 'code-review', elapsed: '—', tokens: '—', updated: 'vor 2 Tagen', desc: 'Erfasse alle alten API-Endpunkte für die schrittweise Migration.', activity: [] },
    ],
  },
  {
    id: 'p3',
    name: 'Customer Onboarding',
    hue: 20,
    jira: { connected: false, url: '' },
    slack: { connected: true, channel: '#onboarding' },
    designMd: '# Onboarding — Tonalität\n\n- Freundlich, knapp, ermutigend\n- Du-Ansprache\n- Emojis sparsam',
    instructions:
      'Antworten in der Sprache des Nutzers. Bei Login-Blockern sofort in Slack eskalieren. Keine internen Tool-Namen nach außen nennen.',
    envs: [
      { key: 'ZENDESK_TOKEN', value: '••••a1b2' },
      { key: 'SLACK_BOT_TOKEN', value: 'xoxb-••••' },
    ],
    jiraInbox: [{ key: 'SUP-77', title: 'Willkommens-E-Mail übersetzen (FR/ES)', type: 'Task' }],
    roles: ['Lead', 'Triage', 'Übersetzung'],
    agents: [
      { id: 'c1', name: 'Echo', role: 'Support Triage', wf: 'Lead', provider: 'claude-sonnet-4.5', status: 'running', skills: ['summarize', 'slack-post'], hue: 20 },
    ],
    tickets: [
      {
        id: 'TCK-04',
        title: 'Triage der offenen Onboarding-Tickets',
        status: 'in_progress',
        prio: 'Hoch',
        agentId: 'c1',
        skill: 'summarize',
        elapsed: '0:47',
        tokens: '6.8k',
        updated: 'vor 2 Min',
        desc: 'Sortiere die offenen Support-Tickets neuer Nutzer nach Dringlichkeit und eskaliere Blocker in Slack.',
        activity: [
          { type: 'skill', time: '11:40', action: 'nutzte summarize', skillName: 'summarize', args: '{ source: "zendesk_open" }', result: '12 offene Tickets zusammengefasst und kategorisiert.', shot: { id: 'p3r1_shot', caption: 'Screenshot: Ticket-Queue in Zendesk' } },
          { type: 'thought', time: '11:40', action: 'priorisierte', text: 'Drei Tickets betreffen einen Login-Blocker — die eskaliere ich sofort.' },
          { type: 'skill', time: '11:41', action: 'nutzte slack-post', skillName: 'slack-post', args: '{ channel: "#onboarding", urgent: true }', result: 'Eskalation mit 3 Tickets in Slack gepostet.' },
          { type: 'message', time: '11:41', action: 'meldete Zwischenstand', text: '12 Tickets triagiert, 3 kritische Login-Blocker an das Team eskaliert. Rest ist in Bearbeitung…' },
        ],
      },
      { id: 'TCK-01', title: 'Slack-Kanal einrichten', status: 'done', prio: 'Mittel', agentId: 'c1', skill: 'slack-post', elapsed: '0:20', tokens: '1.2k', updated: 'gestern', desc: 'Richte den #onboarding-Kanal ein und verbinde die Eskalations-Automation.', activity: [{ type: 'message', time: '09:00', action: 'meldete Abschluss', text: 'Kanal #onboarding erstellt und mit der Triage-Automation verbunden.' }] },
    ],
  },
]

export const initialWizardData = () => ({
  name: '',
  designMd: '# \n\n## Stil\n- \n\n## Struktur\n- ',
  instructions: '',
  jira: { connected: false, url: '' },
  slack: { connected: false, channel: '' },
  envs: [],
})
